## POSTTEST 7


*   Nama    : RISKY KURNIAWAN
*   NIM     : 2009106050
*   Kelas   : A2 (2020)







In [201]:
import tensorflow as tf

### 1. Buatlah sebuah tensor dengan **shape(5,5)** dengan nilai random yang disimpan dalam variable **random_tensor**


In [202]:
# Tensor (5,5) nilai Random
# Karena akan dilakukan perhitungan aritmatika ke dalam tensor ini, maka saya akan menggunakan tf.Variable
random_tensor = tf.Variable(
    tf.random.normal(
        [5,5], 
        mean=3, 
        stddev=1, 
        dtype=tf.float32, 
        seed=10
        )
    )
random_tensor

<tf.Variable 'Variable:0' shape=(5, 5) dtype=float32, numpy=
array([[2.5519788, 4.0903897, 2.8008606, 2.321536 , 3.3817124],
       [2.66678  , 2.5055733, 2.401075 , 2.7427223, 1.6741441],
       [2.5619106, 0.8426664, 3.530834 , 2.981483 , 2.5828128],
       [2.8911448, 4.8377557, 4.6463823, 2.2391694, 3.0192277],
       [2.0741491, 3.3829453, 3.792543 , 2.9179056, 2.9192753]],
      dtype=float32)>

### 2. Buatlah sebuah tensor dengan shape(5,5) dari sebuah list dengan nilai bilangan prima dalam variable prime_tensor

In [203]:
list = [[],[],[],[],[]]
iterasi = 0
# Memasukkan bilangan prima ke dalam list
for num in range(2, 100 + 1):
  for i in range(2, num):
    if (num % i == 0):
      break
  else:
    if (len(list[iterasi]) >= 5): # (5x5)
      iterasi+=1
    list[iterasi].append(int(num))
list

[[2, 3, 5, 7, 11],
 [13, 17, 19, 23, 29],
 [31, 37, 41, 43, 47],
 [53, 59, 61, 67, 71],
 [73, 79, 83, 89, 97]]

In [204]:
prime_tensor = tf.Variable((tf.convert_to_tensor(list, dtype=tf.float32)))
prime_tensor.read_value().numpy()

array([[ 2.,  3.,  5.,  7., 11.],
       [13., 17., 19., 23., 29.],
       [31., 37., 41., 43., 47.],
       [53., 59., 61., 67., 71.],
       [73., 79., 83., 89., 97.]], dtype=float32)

### 3. Tampilkan dimensi dari kedua variable tersebut

In [205]:
# Dimensi kedua Variabel
print(random_tensor.shape)
print(prime_tensor.shape)

(5, 5)
(5, 5)


### 4. Tampilkan hasil dari perhitungan aritmetika 2 variable tersebut (Gunakan minimal 5 operator)## 

In [206]:
# Add
tf.add(random_tensor,prime_tensor).numpy()

array([[ 4.551979 ,  7.0903897,  7.8008604,  9.321536 , 14.381712 ],
       [15.66678  , 19.505573 , 21.401075 , 25.742722 , 30.674145 ],
       [33.561913 , 37.842667 , 44.530834 , 45.981483 , 49.582813 ],
       [55.891144 , 63.837757 , 65.646385 , 69.23917  , 74.019226 ],
       [75.07415  , 82.38294  , 86.79254  , 91.91791  , 99.91927  ]],
      dtype=float32)

In [207]:
# Multiply
tf.multiply(random_tensor,prime_tensor).numpy()

array([[  5.1039577,  12.27117  ,  14.004303 ,  16.250751 ,  37.198837 ],
       [ 34.66814  ,  42.594746 ,  45.620422 ,  63.08261  ,  48.55018  ],
       [ 79.41923  ,  31.178656 , 144.76419  , 128.20377  , 121.392204 ],
       [153.23067  , 285.42758  , 283.42932  , 150.02435  , 214.36517  ],
       [151.41289  , 267.2527   , 314.78107  , 259.6936   , 283.1697   ]],
      dtype=float32)

In [208]:
# Divide
tf.divide(random_tensor,prime_tensor).numpy()

array([[1.2759894 , 1.3634633 , 0.56017214, 0.33164802, 0.3074284 ],
       [0.20513692, 0.14738667, 0.12637237, 0.11924879, 0.05772911],
       [0.08264228, 0.02277477, 0.0861179 , 0.06933682, 0.05495346],
       [0.0545499 , 0.08199586, 0.0761702 , 0.03342044, 0.04252433],
       [0.028413  , 0.04282209, 0.04569329, 0.03278546, 0.03009562]],
      dtype=float32)

In [209]:
# Subtract
tf.subtract(random_tensor,prime_tensor).numpy()

array([[  0.5519788,   1.0903897,  -2.1991394,  -4.678464 ,  -7.6182876],
       [-10.33322  , -14.494427 , -16.598925 , -20.257278 , -27.325855 ],
       [-28.43809  , -36.157333 , -37.469166 , -40.018517 , -44.417187 ],
       [-50.108856 , -54.162243 , -56.35362  , -64.76083  , -67.980774 ],
       [-70.92585  , -75.61706  , -79.20746  , -86.08209  , -94.08073  ]],
      dtype=float32)

In [210]:
# Power of
tf.pow(random_tensor,prime_tensor).numpy()

array([[6.5125957e+00, 6.8437492e+01, 1.7236835e+02, 3.6343607e+02,
        6.6145975e+05],
       [3.4501141e+05, 6.0453415e+06, 1.6893064e+07, 1.1972426e+10,
        3.0902430e+06],
       [4.6289582e+12, 1.7752512e-03, 2.9038159e+22, 2.5153035e+20,
        2.3354339e+19],
       [2.7333881e+24,           inf,           inf, 2.8564403e+23,
        1.1819715e+34],
       [1.3468477e+23,           inf,           inf,           inf,
                  inf]], dtype=float32)

### 5. Tampilkan nilai maksimal dan minimal dari variable random_tensor

In [211]:
tf.argmax(random_tensor, axis=0).numpy()

array([3, 3, 3, 2, 0])

In [212]:
tf.argmin(random_tensor, axis=0).numpy()

array([4, 2, 1, 3, 1])

### 6. Tampilkan hasil dari penggabungan variable random_tensor dengan prime_tensor (concatenation)

In [213]:
print(f"Before : {random_tensor.shape} {prime_tensor.shape}" )

Before : (5, 5) (5, 5)


In [214]:
# Setelah
concat_tensor_1 = tf.concat([random_tensor, prime_tensor], axis=0)
concat_tensor_2 = tf.concat([random_tensor, prime_tensor], axis=1)
print(f"After (axis = 0) : {concat_tensor_1.shape}")
print(f"After (axis = 1) : {concat_tensor_2.shape}")

After (axis = 0) : (10, 5)
After (axis = 1) : (5, 10)


### 7. Tampilkan hasil sorting dari kedua variable di atas. (descending)

In [215]:
# random_tensor
random = tf.sort(random_tensor, direction="DESCENDING").numpy()

# prime_tensor
prime = tf.sort(prime_tensor, direction="DESCENDING").numpy()


print('Random Tensor:\n', random)
print('\n\n')
print('Prime Tensor:\n', prime)

Random Tensor:
 [[4.0903897 3.3817124 2.8008606 2.5519788 2.321536 ]
 [2.7427223 2.66678   2.5055733 2.401075  1.6741441]
 [3.530834  2.981483  2.5828128 2.5619106 0.8426664]
 [4.8377557 4.6463823 3.0192277 2.8911448 2.2391694]
 [3.792543  3.3829453 2.9192753 2.9179056 2.0741491]]



Prime Tensor:
 [[11.  7.  5.  3.  2.]
 [29. 23. 19. 17. 13.]
 [47. 43. 41. 37. 31.]
 [71. 67. 61. 59. 53.]
 [97. 89. 83. 79. 73.]]
